Autoupdate app based on github release (#37)
* Autoupdate app based on github release

* Create script to update AssemblyVersion

* Update to 3.1 version

---------

Co-authored-by: Yeray <Yeray>

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -2,30 +2,27 @@ name: .NET Core Desktop
 
 on:
   push:
-    branches: [ "feature/35/main" ]
+    branches: [ "feature/3.0" ]
 
 jobs:
 
   build:
 
-    runs-on: windows-latest  # For a list of available runner types, refer to
-                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
+    runs-on: windows-latest 
 
     env:
-      Solution_Name: Library\CommonScripts.sln
       App_Project_Path: Library\App\App.csproj
       App_PublishProfile_Path: Library\App\Properties\PublishProfiles\ProjectBuild.pubxml
       Inno_Setup_Path: ./Deployment/Setup.iss
       Inno_Setup_Tmp_Path: ./Deployment/Setup.tmp.iss
       Configuration: Release
-
+    
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
 
-    # Install the .NET Core workload
     - name: Install .NET Core
       uses: actions/setup-dotnet@v3
       with:
@@ -134,3 +131,41 @@ jobs:
         asset_content_type: application/zip
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Update gist for AutoUpdater.NET
+      id: update_gist_for_autoupdater
+      env:
+        GITHUB_TOKEN: ${{ secrets.GIST_GITHUB_TOKEN }}
+        gistId: 484fa8d7871d44d1f67cc68a2c7d082f
+        gistName: CommonScripts_LastVersion.xml
+      run: |
+        $tag_name="${{ steps.get_version.outputs.version }}"
+        $apiHeaders=@{"Authorization"="Bearer $env:GITHUB_TOKEN"}
+        $updateGistEndpoint="https://api.github.com/gists/$env:gistId"
+        $gistContent = @"
+        <?xml version="1.0" encoding="UTF-8"?>
+        <item>
+          <version>$tag_name</version>
+          <url>https://github.com/yeray697/CommonScriptsContainer/releases/download/$tag_name/App.zip</url>
+          <changelog>https://github.com/yeray697/CommonScriptsContainer/releases</changelog>
+          <mandatory>false</mandatory>
+        </item>
+        "@
+        $postParams = @{
+          description = "XML for AutoUpdater.NET, used in CommonScriptsContainer application. Current version $tag_name";
+          files       = @{
+            $env:gistName = @{
+              content = $gistContent
+            }
+          }
+        }
+        $postParams = $postParams | ConvertTo-Json -Depth 2
+        $result = Invoke-WebRequest -Headers $apiHeaders -SkipHttpErrorCheck -Uri $updateGistEndpoint -Method POST -Body $postParams
+
+        if ($result.StatusCode -ne 200)
+        {
+            echo "Invalid status code"
+            echo $result
+            exit 1
+        }
+        echo "Gist updated successfully"
