Automate CI

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -1,41 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
-# built on .NET Core.
-# To learn how to migrate your existing application to .NET Core,
-# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
-#
-# To configure this workflow:
-#
-# 1. Configure environment variables
-# GitHub sets default environment variables for every workflow run.
-# Replace the variables relative to your project in the "env" section below.
-#
-# 2. Signing
-# Generate a signing certificate in the Windows Application
-# Packaging Project or add an existing signing certificate to the project.
-# Next, use PowerShell to encode the .pfx file using Base64 encoding
-# by running the following Powershell script to generate the output string:
-#
-# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
-# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
-#
-# Open the output file, SigningCertificate_Encoded.txt, and copy the
-# string inside. Then, add the string to the repo as a GitHub secret
-# and name it "Base64_Encoded_Pfx."
-# For more information on how to configure your signing certificate for
-# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
-#
-# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
-# See "Build the Windows Application Packaging project" below to see how the secret is used.
-#
-# For more information on GitHub Actions, refer to https://github.com/features/actions
-# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
-# refer to https://github.com/microsoft/github-actions-for-desktop-apps
-
 name: .NET Core Desktop
 
 on:
@@ -46,10 +8,6 @@ jobs:
 
   build:
 
-    strategy:
-      matrix:
-        configuration: [Debug, Release]
-
     runs-on: windows-latest  # For a list of available runner types, refer to
                              # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
 
@@ -57,6 +15,9 @@ jobs:
       Solution_Name: Library\CommonScripts.sln
       App_Project_Path: Library\App\App.csproj
       App_PublishProfile_Path: Library\App\Properties\PublishProfiles\ProjectBuild.pubxml
+      Inno_Setup_Path: ./Deployment/Setup.iss
+      Inno_Setup_Tmp_Path: ./Deployment/Setup.tmp.iss
+      Configuration: Release
 
     steps:
     - name: Checkout
@@ -69,22 +30,107 @@ jobs:
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 6.0.x
-
-    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
-    - name: Setup MSBuild.exe
-      uses: microsoft/setup-msbuild@v1.0.2
-
-    # Restore the application to populate the obj folder with RuntimeIdentifiers
-    - name: Restore the application
-      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
-      env:
-        Configuration: ${{ matrix.configuration }}
-
-    # Create the app package by building and packaging the Windows Application Packaging project
+        
+    - name: Get App version
+      id: get_version
+      run: echo "version=$(([Xml] (Get-Content $env:App_Project_Path)).Project.PropertyGroup.AssemblyVersion)" >> $env:GITHUB_OUTPUT
+      
     - name: Create the app package
-      run: msbuild $env:App_Project_Path /p:Configuration=$env:Configuration /t:publish /p:PublishProfile=$env:App_PublishProfile_Path
+      run: dotnet publish $env:App_Project_Path -c $env:Configuration /p:PublishProfile=$env:App_PublishProfile_Path
+
+    - name: Create Zip Archive
+      run: Compress-Archive -Path ./Library/App/Build/* -DestinationPath ./app-publish.zip
+      
+    - name: Prepare Inno Setup file
+      id: prepare_inno_setup
+      run: |
+        $innoVariables = "#define AppMode ""${{ env.configuration }}""`r`n#define ApplicationVersion ""${{ steps.get_version.outputs.version }}""`r`n";
+        $innoVariables + (Get-Content ${{ env.Inno_Setup_Path }} -Raw) | Set-Content ${{ env.Inno_Setup_Tmp_Path }}
+      
+    - name: Build Setup.exe with Inno Setup
+      uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
+      with:
+        filepath: ${{ env.Inno_Setup_Tmp_Path }}
+      
+    - name: Create or Update Release
+      id: create_or_update_release
       env:
-        Appx_Bundle: Always
-        Appx_Bundle_Platforms: x86|x64
-        Appx_Package_Build_Mode: StoreUpload
-        Configuration: ${{ matrix.configuration }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        $tag_name="${{ steps.get_version.outputs.version }}"
+        $release_name="Release $tag_name"
+        $prerelease="false"
+        $draft="true"
+        $apiHeaders=@{"Authorization"="Bearer $env:GITHUB_TOKEN"}
+        $githubRepository=$env:GITHUB_REPOSITORY
+        $getReleasesEndpoint="https://api.github.com/repos/$githubRepository/releases"
+        
+        # Cannot use the "Find Release by Tag" endpoint as it does not find draft releases.
+        # Instead, getting all releases and manually filter by tag
+        $result = Invoke-WebRequest -Headers $apiHeaders -SkipHttpErrorCheck -Uri $getReleasesEndpoint
+
+        if ($result.StatusCode -ne 200)
+        {
+            echo "Invalid status code"
+            echo $result
+            exit 1
+        }
+        
+        echo "Checking if release with tag $tag_name already exists"
+        $findRelease = $result.Content | ConvertFrom-Json | Where-Object { $_.tag_name -eq $tag_name }
+        
+        if (!$findRelease)
+        {
+          echo "Release does not exist"
+          echo "Creating new release as draft"
+          $createReleaseEndpoint="https://api.github.com/repos/$githubRepository/releases"
+          $postParams = @"
+          { 
+            "tag_name": "$tag_name",
+            "name": "$release_name",
+            "draft": $draft,
+            "prerelease": $prerelease
+          }
+        "@
+          $result = Invoke-WebRequest -Headers $apiHeaders -SkipHttpErrorCheck -Uri $createReleaseEndpoint -Method POST -Body $postParams
+          if ($result.StatusCode -ne 201)
+          {
+            echo "Invalid status code"
+            echo $result
+            exit 1
+          }
+          echo "Release created"
+          $resultAsJson = $result.Content  | ConvertFrom-Json 
+          $uploadUrl = $resultAsJson.upload_url;
+        }
+        elseif (!$findRelease.draft)
+        {
+          echo "A release with tag $tag_name already exists and is not a draft"
+          exit 1
+        }
+        else
+        {
+          $uploadUrl = $findRelease.upload_url;
+          echo "Release already exists and is a draft version. Updating assets in the next build step."
+        }
+        echo "upload_url=$uploadUrl" >> $env:GITHUB_OUTPUT
+
+    - name: Upload Setup.exe Release Asset
+      uses: actions/upload-release-asset@v1
+      with:
+        upload_url: ${{ steps.create_or_update_release.outputs.upload_url }}
+        asset_path: ./Deployment/Output/CommonScripts_Installer_${{ steps.get_version.outputs.version}}.exe
+        asset_name: CommonScripts_Installer_${{ steps.get_version.outputs.version}}.exe
+        asset_content_type: octet-stream
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Upload Published App Release Asset
+      uses: actions/upload-release-asset@v1
+      with:
+        upload_url: ${{ steps.create_or_update_release.outputs.upload_url }}
+        asset_path: ./app-publish.zip
+        asset_name: App.zip
+        asset_content_type: application/zip
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
